# Site settings
title: Dsm | A simple blog of ml technical sharings
description: "A simple blog of ml technical sharings"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Daniel Liu"
  email: "danielshaving@gmail.com"
  url: "http://www.danielshaving.com"
  avatar: "https://ooo.0o0.ooo/2017/05/26/5928368d409dd.png"

# Build settings
baseurl: /dsm # Change this to your relative path (ex: /blog/), or leave just a /
indexurl: /dsm/index.html
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
